In [50]:
import requests
from bs4 import BeautifulSoup
r = requests.get('https://www.imdb.com/title/tt0181836/')
soup = BeautifulSoup(r.content, 'html.parser')

In [119]:
divs = soup.find_all('div',class_='txt-block')[8] # first level to narrow
#clean returned string value and turn into an integer to fill in missing budget in our dataset
int(divs.text.replace('\nBudget:$', '').replace(' ', '').replace('\n(estimated)\n', '').replace(',',''))

1000000

In [ ]:
divs

In [121]:
df = pd.read_csv('movieDB_API_movies.csv')
df[df['budget']==0] # we are running into some budgets and revenues returning 0 values

,Unnamed: 0,budget,genres,id,imdb_id,popularity,release_date,revenue,runtime,title,vote_average,vote_count
6,6,0,"['Romance', 'Animation', 'Drama']",372058,tt5311514,29.292,2016-08-26,357986087,106.0,Your Name.,8.5,5018
17,17,0,"['Adventure', 'Comedy']",40096,tt0271383,9.056,2000-09-15,0,104.0,A Dog's Will,8.4,568
24,24,0,"['Drama', 'Romance']",11216,tt0095765,14.666,1988-11-17,11990401,124.0,Cinema Paradiso,8.4,2077
26,26,0,"['Comedy', 'Drama']",579245,tt8655470,24.981,2019-10-23,0,114.0,The Specials,8.4,216
31,31,0,"['Drama', 'Science Fiction', 'Animation']",18491,tt0169858,12.520,1997-07-19,20000000,87.0,Neon Genesis Evangelion: The End of Evangelion,8.4,483
34,34,0,"['Drama', 'Mystery']",432517,tt3845892,8.352,2017-01-15,0,90.0,Sherlock: The Final Problem,8.4,764
36,36,0,['Drama'],3782,tt0044741,11.395,1952-10-09,55240,143.0,Ikiru,8.4,459
38,38,0,['Drama'],18148,tt0046438,10.696,1953-11-03,0,134.0,Tokyo Story,8.4,431
40,40,0,"['Drama', 'Romance']",11659,tt0346336,8.599,2003-06-22,2693053,366.0,The Best of Youth,8.4,261
41,41,0,"['Animation', 'Family', 'Adventure', 'Comedy']",508965,tt4729430,26.087,2019-11-08,0,96.0,Klaus,8.3,1401
42,42,0,"['Science Fiction', 'Adventure']",313106,tt2779318,9.891,2013-11-23,0,77.0,Doctor Who: The Day of the Doctor,8.4,545
44,44,0,"['Drama', 'Mystery', 'Crime']",452522,tt0278784,8.237,1989-12-31,0,112.0,Twin Peaks,8.3,348
46,46,0,"['Action', 'Drama', 'History']",14537,tt0056058,10.650,1962-09-15,0,135.0,Harakiri,8.3,314
51,51,0,['Drama'],797,tt0060827,11.320,1966-10-18,0,85.0,Persona,8.3,911
52,52,0,"['Crime', 'Drama', 'Mystery', 'Thriller']",12493,tt0057565,11.203,1963-03-01,0,142.0,High and Low,8.3,268
53,53,0,['Comedy'],20914,tt0072637,6.633,1975-08-15,0,140.0,My Friends,8.3,365
54,54,0,"['Drama', 'Crime']",26451,tt0065889,8.263,1970-11-13,0,115.0,Investigation of a Citizen Above Suspicion,8.3,300
58,58,0,"['Drama', 'History', 'War']",25237,tt0091251,10.780,1985-07-01,0,142.0,Come and See,8.3,412
60,60,0,"['Drama', 'Romance']",531428,tt8613070,34.575,2019-06-17,0,119.0,Portrait of a Lady on Fire,8.3,336
63,63,0,"['Drama', 'History']",895,tt0060107,10.548,1966-12-16,0,206.0,Andrei Rublev,8.3,334
64,64,0,"['Drama', 'Comedy']",24188,tt0056512,6.780,1962-12-04,0,105.0,Il Sorpasso,8.3,296
70,70,0,"['Science Fiction', 'Drama']",1398,tt0079944,16.578,1979-05-25,0,163.0,Stalker,8.3,888
71,71,0,"['Comedy', 'Crime']",24382,tt0052216,7.325,1958-06-06,0,106.0,Big Deal on Madonna Street,8.3,326
74,74,0,"['Family', 'Animation', 'Romance', 'Comedy']",455661,tt6969946,5.964,2017-06-01,0,4.0,In a Heartbeat,8.3,762
78,78,0,"['Fantasy', 'Drama']",422,tt0056801,15.171,1963-02-14,0,139.0,8½,8.3,1080
80,80,0,"['Mystery', 'Western', 'Thriller']",446159,tt2762506,13.428,2019-08-29,0,132.0,Bacurau,8.3,315
82,82,0,"['Drama', 'Animation', 'Romance']",378064,tt5323662,11.011,2016-09-17,310407,130.0,A Silent Voice,8.3,1376
90,90,0,"['Action', 'Comedy', 'Mystery']",992,tt0015324,10.001,1924-04-19,0,49.0,"Sherlock, Jr.",8.2,371
95,95,0,"['Animation', 'Drama', 'Family', 'Fantasy']",110420,tt2140203,12.463,2012-07-21,0,117.0,Wolf Children,8.2,1218
96,96,0,"['Fantasy', 'Drama']",490,tt0050976,13.928,1957-02-16,0,96.0,The Seventh Seal,8.2,1391
...,...,...,...,...,...,...,...,...,...,...,...,...
6855,6855,0,"['Action', 'TV Movie', 'Science Fiction', 'Com...",331446,tt3899796,7.826,2015-07-22,0,88.0,Sharknado 3: Oh Hell No!,4.5,292
6857,6857,0,"['Thriller', 'Horror', 'Science Fiction']",248504,tt3062074,7.454,2014-07-30,0,86.0,Sharknado 2: The Second One,4.4,389
6861,6861,0,[],60556,tt1738298,8.668,2010-12-20,0,105.0,Natale in Sudafrica,4.4,218
6862,6862,0,['Comedy'],244688,tt3138104,3.238,2014-02-01,0,86.0,The Hungover Games,4.4,220
6864,6864,0,"['Comedy', 'Drama']",535437,tt4867110,9.183,2018-11-06,0,93.0,Swiped,4.4,411
6865,6865,0,"['Horror', 'Thriller']",267806,tt3704538,5.896,2014-10-23,2756,81.0,V/H/S: Viral,4.4,290
6868,6868,0,"['Comedy', 'Crime']",11546,tt0110857,9.353,1994-06-09,126247,83.0,Police Academy: Mission to Moscow,4.4,440
6879,6879,0,"['Fantasy', 'Action', 'Adventure', 'Science Fi...",13486,tt1104123,10.559,2008-07-19,0,109.0,The Scorpion King 2: Rise of a Warrior,4.3,332
6880,6880,0,"['Comedy', 'Horror', 'Science Fiction']",390989,tt4831420,10.061,2016-07-31,0,85.0,Sharknado 4: The 4th Awakens,4.3,223
6885,6885,0,"['Crime', 'Comedy', 'Family']",12536,tt0329200,12.054,2003-11-26,0,89.0,Home Alone 4,4.3,641
6886,6886,0,['Comedy'],18955,tt1262877,5.581,2009-07-21,0,95.0,Coco,4.3,362
6888,6888,0,['Comedy'],13727,tt0953369,7.611,2008-04-02,0,103.0,Disco,4.3,222
6889,6889,0,"['Mystery', 'Thriller', 'Horror']",11531,tt0229260,9.989,2000-10-27,0,90.0,Book of Shadows: Blair Witch 2,4.3,420
6891,6891,0,"['Mystery', 'Science Fiction', 'Thriller']",332502,tt3774790,8.752,2015-10-29,0,91.0,400 Days,4.3,325
6893,6893,0,['Comedy'],375798,tt5029602,5.527,2016-10-19,0,95.0,Brice 3,4.2,428
6896,6896,0,"['Adventure', 'Comedy', 'Family']",26264,tt0322389,8.276,2003-08-18,0,87.0,George of the Jungle 2,4.2,265
6897,6897,0,"['Comedy', 'Drama']",37265,tt0104014,7.655,1992-02-21,0,93.0,All Ladies Do It,4.2,208
6898,6898,0,['Horror'],119278,tt2025667,5.928,2012-10-12,0,90.0,Smiley,4.2,220
6903,6903,0,"['Horror', 'Thriller']",407559,tt5059406,7.589,2016-09-10,0,89.0,I Am the Pretty Thing That Lives in the House,4.1,334
6910,6910,0,['Science Fiction'],11867,tt0115624,11.316,1996-05-02,3793614,98.0,Barb Wire,4.1,212
6911,6911,0,['Horror'],400411,tt4796122,7.212,2016-07-01,252,84.0,Satanic,4.1,288
6916,6916,0,['Drama'],13461,tt0443584,16.795,2005-11-18,5151936,100.0,Melissa P.,4.1,312
6918,6918,0,['Comedy'],21435,tt0445800,7.767,2006-02-01,0,95.0,French Fried Vacation 3,4.0,486
6924,6924,0,['Comedy'],419507,tt6281538,5.305,2016-12-15,0,86.0,Fuga da Reuma Park,3.9,305
6930,6930,0,"['Horror', 'Drama', 'Mystery', 'Thriller']",505423,tt5913798,12.158,2019-01-26,0,94.0,Wounds,3.9,321
6932,6932,0,['Comedy'],238930,tt3040510,4.931,2013-11-21,0,0.0,Fuga di cervelli,3.8,327
6939,6939,0,"['Thriller', 'Horror']",485774,tt7608028,7.653,2018-01-19,0,94.0,The Open House,3.7,933
6941,6941,0,['Horror'],94365,tt1883367,13.499,2015-05-22,0,103.0,The Human Centipede 3 (Final Sequence),3.6,379
6942,6942,0,['Horror'],26914,tt0105643,6.442,1990-10-12,0,95.0,Troll 2,3.6,221
6946,6946,0,"['Adventure', 'Comedy', 'Family', 'Science Fic...",74849,tt0193524,9.858,1978-12-01,0,97.0,The Star Wars Holiday Special,3.1,226

In [124]:
df.head()

,Unnamed: 0,budget,genres,id,imdb_id,popularity,release_date,revenue,runtime,title,vote_average,vote_count
0,0,13200000,"['Comedy', 'Drama', 'Romance']",19404,tt0112870,17.437,1995-10-20,100000000,190.0,Dilwale Dulhania Le Jayenge,8.8,2214
1,1,25000000,"['Drama', 'Crime']",278,tt0111161,35.028,1994-09-23,28341469,142.0,The Shawshank Redemption,8.7,15045
2,2,6000000,"['Drama', 'Crime']",238,tt0068646,29.433,1972-03-14,245066411,175.0,The Godfather,8.7,11486
3,3,11363000,"['Comedy', 'Thriller', 'Drama']",496243,tt6751668,176.819,2019-05-30,201055038,132.0,Parasite,8.6,4751
4,4,22000000,"['Drama', 'History', 'War']",424,tt0108052,19.641,1993-11-30,321365567,195.0,Schindler's List,8.6,9163